language: dart
dart:
  - stable
  - dev

cache:
  directories:
    - $HOME/.pub-cache
    - .dart_tool/build

before_install:
  - git clone https://github.com/flutter/flutter.git -b stable $HOME/flutter
  - export PATH=$HOME/flutter/bin:$HOME/flutter/bin/cache/dart-sdk/bin:$PATH

install:
  - flutter pub get

script:
  - flutter pub run build_runner build --delete-conflicting-outputs --fail-on-severe
  - flutter analyze
  - flutter pub run test_coverage --no-badge
  - flutter pub run remove_from_coverage -f coverage/lcov.info -r ".g.dart$" -r ".freezed.dart$"
  - dartdoc --no-generate-docs
  - pub publish --dry-run

after_success:
  - bash <(curl -s https://codecov.io/bash)
