include: package:pedantic/analysis_options.1.9.0.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true
  errors:
    # TODO https://github.com/dart-lang/sdk/issues/35831
    include_file_not_found: ignore

linter:
  # Rules: http://dart-lang.github.io/linter/lints
  rules:
    prefer_single_quotes: false
